<?php /** @var gamboamartin\comercial\controllers\controlador_com_cliente $controlador  controlador en ejecucion */ ?>
<?php use config\views; ?>
<?php echo $controlador->inputs->documento; ?>
<?php echo $controlador->inputs->com_tipo_cliente_id; ?>
<?php echo $controlador->inputs->cat_sat_actividad_economica_id; ?>
<?php echo $controlador->inputs->iva; ?>
<?php echo $controlador->inputs->codigo; ?>
<?php echo $controlador->inputs->razon_social; ?>
<?php echo $controlador->inputs->com_cliente_rfc; ?>
<?php echo $controlador->inputs->telefono; ?>
<input type="hidden" name="tipo_persona" id="tipo_persona">
<input type="hidden" name="regimen_fiscal" id="regimen_fiscal">
<input type="hidden" name="estado" id="estado">
<input type="hidden" name="municipio" id="municipio">
<input type="hidden" name="cp" id="cp">
<input type="hidden" name="colonia" id="colonia">
<input type="hidden" name="calle" id="calle">
<input type="hidden" name="numero_exterior" id="numero_exterior">
<input type="hidden" name="numero_interior" id="numero_interior">
<?php include (new views())->ruta_templates.'botons/submit/alta_bd.php';?>